# -*- coding: utf-8 -*-
# Copyright (c) 2025, BrainWise and contributors
# For license information, please see license.txt

import frappe
from frappe.model.document import Document


class OfflineInvoiceSync(Document):
    """
    Tracks offline invoice synchronization to prevent duplicate submissions.

    Each record maps an offline_id (generated client-side) to a Sales Invoice,
    allowing the system to detect and prevent duplicate sync attempts.
    """

    def before_insert(self):
        """Only stamp synced_at after an invoice has actually been synced."""
        if self.status == "Synced" and not self.synced_at:
            self.synced_at = frappe.utils.now_datetime()

    @staticmethod
    def create_sync_record(offline_id, sales_invoice, pos_profile=None, customer=None, status="Synced"):
        """
        Create a sync record for an offline invoice.

        Args:
            offline_id: The unique offline ID generated by the client
            sales_invoice: The Sales Invoice name created on the server
            pos_profile: Optional POS Profile name
            customer: Optional Customer name
            status: Sync status - "Pending", "Synced", or "Failed"

        Returns:
            The created OfflineInvoiceSync document or existing one if duplicate
        """
        if not offline_id:
            return None

        # Check if record already exists. offline_id is unique at the database
        # level, so every retry converges on the same tracking document.
        existing = frappe.db.get_value(
            "Offline Invoice Sync",
            {"offline_id": offline_id},
            ["name", "sales_invoice", "status", "pos_profile", "customer"],
            as_dict=True
        )

        if existing:
            sync_doc = frappe.get_doc("Offline Invoice Sync", existing.name)
            changed = False

            if sales_invoice and sync_doc.sales_invoice != sales_invoice:
                sync_doc.sales_invoice = sales_invoice
                changed = True
            if pos_profile and sync_doc.pos_profile != pos_profile:
                sync_doc.pos_profile = pos_profile
                changed = True
            if customer and sync_doc.customer != customer:
                sync_doc.customer = customer
                changed = True
            if status and sync_doc.status != status:
                sync_doc.status = status
                changed = True

            if status == "Synced":
                sync_doc.synced_at = frappe.utils.now_datetime()
                changed = True

            if changed:
                sync_doc.flags.ignore_permissions = True
                sync_doc.save()

            return sync_doc

        doc = frappe.get_doc({
            "doctype": "Offline Invoice Sync",
            "offline_id": offline_id,
            "sales_invoice": sales_invoice or "",
            "pos_profile": pos_profile,
            "customer": customer,
            "status": status,
        })
        doc.flags.ignore_permissions = True
        doc.insert()
        return doc

    @staticmethod
    def get_state(offline_id):
        """Return the complete server-side state for an offline identifier."""
        if not offline_id:
            return {
                "exists": False,
                "synced": False,
                "sales_invoice": None,
                "status": None,
            }

        existing = frappe.db.get_value(
            "Offline Invoice Sync",
            {"offline_id": offline_id},
            ["name", "sales_invoice", "status", "pos_profile", "customer"],
            as_dict=True,
        )

        if not existing:
            return {
                "exists": False,
                "synced": False,
                "sales_invoice": None,
                "status": None,
            }

        is_synced = bool(existing.status == "Synced" and existing.sales_invoice)
        return {
            "exists": True,
            "synced": is_synced,
            "sales_invoice": existing.sales_invoice or None,
            "status": existing.status,
            "name": existing.name,
            "pos_profile": existing.pos_profile,
            "customer": existing.customer,
        }

    @staticmethod
    def is_synced(offline_id):
        """Backward-compatible helper used by older callers."""
        state = OfflineInvoiceSync.get_state(offline_id)
        return {
            "synced": state.get("synced", False),
            "sales_invoice": state.get("sales_invoice"),
            "status": state.get("status"),
        }
